version: '3.1'
services:
    zookeeper:
        image: zuora/zookeeper
        restart: always
        ports:
            - 2181:2181
        environment:
            SERVICE_NAME: local_fjord_zookeeper
            SERVICE_PLANET: Mars
            SERVICE_DEPARTMENT: DevOps
            SERVICE_DATA_CENTER: aws
            INTERVAL_IN_SEC: 10
            TRANSLATOR_FULL_CLASS_NAME: io.porter.jmx.translate.translators.JmxToMicroMeterTranslator
            BROKER_SERVERS_URL: speed-racer-kafka.zeta.tools:9092
            TOPIC_NAME: micrometer-wavefront
